Inventario-master1/Inventario-master/inventario/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.core.validators import MinLengthValidator, MaxLengthValidator


class PerfilUsuario(AbstractUser):
    JEFEBODEGA = 'JF'
    BODEGUERO = 'BD'
    ROLES_USUARIO = [
        (JEFEBODEGA, 'Jefe de Bodega'),
        (BODEGUERO, 'Bodeguero'),
    ]
    rol = models.CharField(max_length=50, choices=ROLES_USUARIO, default=BODEGUERO)

    def es_jefe_bodega(self):
        return self.rol == self.JEFEBODEGA

    def es_bodeguero(self):
        return self.rol == self.BODEGUERO

    groups = models.ManyToManyField(Group, related_name='perfil_usuarios')
    user_permissions = models.ManyToManyField(Permission, related_name='perfil_usuarios')

class Bodega(models.Model):
    nombre = models.CharField(max_length=50)
    direccion = models.CharField(max_length=50, default='Valor predeterminado')
    jefe_bodega = models.ForeignKey(PerfilUsuario, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.nombre

    def stock_producto(self, producto):
        # Actualizar para usar el nuevo modelo ProductoBodega
        relacion = self.producto_bodega.filter(producto=producto).first()
        return relacion.stock if relacion else 0


class Producto(models.Model):
    nombre = models.CharField(
        max_length=50,
        validators=[
            MinLengthValidator(1),
            MaxLengthValidator(50),
        ]
    )
    descripcion = models.TextField(
        validators=[
            MaxLengthValidator(400),
        ]
    )
    cantidad_total = models.IntegerField(default=0)  # Campo añadido

    def __str__(self):
        return self.nombre.lower()
    
class ProductoBodega(models.Model):
    bodega = models.ForeignKey(Bodega, on_delete=models.CASCADE, related_name='producto_bodega')
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, related_name='bodega_producto')
    stock = models.IntegerField(default=0)

    class Meta:
        unique_together = ('bodega', 'producto')

    def __str__(self):
        return f"{self.producto.nombre} en {self.bodega.nombre} - Stock: {self.stock}"

class Movimiento(models.Model):
    bodega_origen = models.ForeignKey(Bodega, on_delete=models.CASCADE, related_name='movimientos_salida')
    bodega_destino = models.ForeignKey(Bodega, on_delete=models.CASCADE, related_name='movimientos_entrada')
    productos = models.ManyToManyField(Producto, through='DetalleMovimiento')
    cantidad = models.IntegerField(default=0)
    usuario = models.ForeignKey(PerfilUsuario, on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now_add=True)

class DetalleMovimiento(models.Model):
    movimiento = models.ForeignKey(Movimiento, on_delete=models.CASCADE, blank=True, null=True)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=0)

Inventario-master1/Inventario-master/inventario/templates/lista_productos.html
{% extends 'profile.html' %}

{% block content %}
  <style>
    .lista-productos-container {
      display: flex;
      flex-direction: column;
      align-items: center;
      margin-top: 50px;
    }

    .titulo-tabla {
      font-size: 24px;
      font-weight: bold;
      margin-bottom: 20px;
      color: #333; /* Cambio de color del título */
      text-transform: uppercase; /* Texto en mayúsculas */
      border-bottom: 2px solid #5C4033; /* Línea decorativa debajo del título */
      padding-bottom: 10px;
    }

    .lista-productos-table {
      width: 80%;
      border-collapse: collapse;
      margin-top: 20px;
    }

    .lista-productos-table th,
    .lista-productos-table td {
      border: 1px solid #ccc;
      background-color: #f9f9f9; /* Fondo ligeramente más claro */
      padding: 15px;
      text-align: center;
    }

    .lista-productos-table th {
      background-color: #5C4033;
      color: #ffffff;
      margin-bottom: 15px;
    }

    .acciones-link {
      color: #5C4033;
      text-decoration: none;
      font-weight: bold;
      margin-right: 10px; /* Espacio entre los enlaces de acciones */
    }

    .acciones-link:hover {
      color: #90ff17;
    }
  </style>

  <div class="lista-productos-container">
    <h1 class="titulo-tabla">Lista de Productos</h1>
    <table class="lista-productos-table">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Descripción</th>
          <th>Cantidad Total</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody>
        {% for producto in productos %}
          <tr>
            <td>{{ producto.nombre }}</td>
            <td>{{ producto.descripcion }}</td>
            <td>{{ producto.cantidad_total }}</td>
            <td>
              <a href="{% url 'detalles_producto' pk=producto.pk %}" class="acciones-link">Detalles</a>
              <a href="{% url 'actualizar_producto' pk=producto.pk %}" class="acciones-link">Actualizar</a>
              <a href="{% url 'eliminar_producto' pk=producto.pk %}" class="acciones-link">Eliminar</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

Inventario-master1/Inventario-master/inventario/templates/profile.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="2897785.ico" type="image/x-icon">
    {% load static %}
    <link rel="icon" type="image/png" href="{% static 'images/2897785.ico' %}">
    <title>Mi Sitio</title>
    <style>
        body {
            background-image: url('https://w.wallhaven.cc/full/ym/wallhaven-ymg5kg.jpg');
            margin: 0;
            padding: 0;
            background-repeat: no-repeat;
            background-size: cover;
        }

        .header {
            background-color: #5C4033;
            color: #ffffff;
            padding: 10px 20px;
            border-bottom: 2px solid #ffffff;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .header_login {
            display: flex;
            align-items: center;
        }

        .login-button {
            background-color: #00755c;
            color: #ffffff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
            border: none;
            border-radius: 5px;
            padding: 10px 20px;
            font-weight: bold;
            text-decoration: none;
            transition: background-color 0.3s ease;
            margin-left: 10px;
        }

        .login-button:hover {
            background-color: #27ae60;
        }

        nav {
            background-color: #5C4033;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
            border-bottom: 2px solid #ffffff;
        }

        .navegation ul {
            list-style: none;
            padding: 0;
            margin: 0;
            display: flex;
            justify-content: center;
        }

        .navegation li {
            margin: 10px;
        }

        .navegation a {
            text-decoration: none;
            color: #ffffff;
            font-weight: bold;
            padding: 10px 20px;
            border-radius: 5px;
            transition: background-color 0.3s ease;
        }

        .navegation a:hover {
            background-color: #27ae60;
        }

        .dropdown {
            display: inline-block;
        }

        .dropbtn {
            background-color: #5C4033;
            color: #ffffff;
            padding: 10px;
            font-size: 16px;
            border: none;
            cursor: pointer;
            border-radius: 5px;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #5C4033;
            box-shadow: 0 8px 16px 0 rgba(0, 0, 0, 0.2);
            z-index: 1;
            border-radius: 5px;
        }

        .dropdown-content a {
            color: #ffffff;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
            border-radius: 5px;
        }

        .dropdown-content a:hover {
            background-color: #27ae60;
        }

        .dropdown:hover .dropdown-content {
            display: block;
        }

        .dropdown:hover .dropbtn {
            background-color: #27ae60;
        }

        .footer {
            background-color: #41292C;
            color: #D1CBD0;
            text-align: center;
            padding: 10px;
            position: fixed;
            bottom: 0;
            width: 100%;
            display: flex;
            justify-content: center;
            align-items: center;
            border-top: 0px solid #ffffff;
        }

        .footer p {
            margin: 5px 20px;
        }

        .contact-info {
            display: flex;
            justify-content: center;
            align-items: center;
            margin: 0 20px;
        }

        .contact-info p {
            margin: 5px;
        }
    </style>
</head>

<body>
    <div class="header">
        <div class="header_login">
            <a href="/logout" class="login-button">logout</a>
        </div>
        <div class="form-container">
            <h2 class="perfil-usuario-heading">Perfil de Usuario</h2>
            <div class="perfil-info">
                <p><strong>Nombre de usuario:</strong> {{ perfil_usuario.username }}</p>
                <p><strong>Rol:</strong> {{ perfil_usuario.get_rol_display }}</p>
            </div>
        </div>
    </div>

    <div class="dropdown">
        <button class="dropbtn">Gestión de Bodegas</button>
        <div class="dropdown-content">
            <a href="{% url 'lista_bodegas' %}">Lista de Bodegas</a>
            <a href="{% url 'crear_actualizar_bodega' %}">Crear Bodega</a>
        </div>
    </div>
    <div class="dropdown">
        <button class="dropbtn">Productos</button>
        <div class="dropdown-content">
            <a href="{% url 'anadir_producto_bodega' %}">Anadir producto</a>
            <a href="{% url 'lista_productos' %}">Lista de Productos</a>
            <a href="{% url 'crear_producto' %}">Crear Producto</a>
        </div>
    </div>
    <div class="dropdown">
        <button class="dropbtn">Movimientos</button>
        <div class="dropdown-content">
            <a href="{% url 'realizar_movimiento' %}">Realizar Movimiento</a>
            <a href="{% url 'historial_movimientos' %}">Historial de Movimientos</a>
        </div>
    </div>
</body>

<footer class="footer">
    <div class="contact-info">
        <p>Correo: inventario@soporte.cl</p>
        <p>Teléfono: +56937062288</p>
    </div>
</footer>

{% block content %}
{% endblock %}

</html>